name: 'tracking-reference-client-v2: cd'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACTS_PUBLIC_SA_KEY }}
      - name: setup gcloud env
        uses: google-github-actions/setup-gcloud@v1
      - name: Install ldid for codesigning
        uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2
      - name: Set up QEMU for emulation
        uses: docker/setup-qemu-action@v3
      - name: install dependecies
        run: yarn
      - name: build linux amd64 binary
        run: yarn build && yarn pkg
      - name: persist artifact
        uses: actions/upload-artifact@v2
        with:
          name: tracking-reference-client-v2
          path: lib/bin