name: 'tracking-reference-client-v2: ci'

on:
  pull_request:
    branches: ['main']

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install deps
        run: yarn
      - name: lint code
        run: yarn run lint
      - name: build code
        run: yarn run build
