name: Second Spectrum Client CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: gcp auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: build and publish
        shell: bash
        run: |
          version=$(cat package.json | jq -r '.version')
          echo $version
          echo "$version"

          yarn

          cat >> .env << 'END'
          RELEASE_BUCKET=second-spectrum-rest-api
          END

          node publish $version
